BUILTIN_COUNTS = [
    # badness technically not count, but whatever
    "hbadness",
    "vbadness",
    "penalty",
    "clubpenalty",
    "widowpenalty",
    "hyphenpenalty",
    "@secpenalty",
    "discretionarypenalty",
    "interfootnotelinepenalty",
    "interlinepenalty",
    "floatingpenalty",
    "lastpenalty",
    "spacefactor",
    "@lowpenalty",
    "@medpenalty",
    "@highpenalty",
    "@beginparpenalty",
    "@endparpenalty",
    "@itempenalty",
    #
    "@tempcnta",
    "@tempcntb",
    "@tempcntc",
    "count@",
]
