# These commands should not be overrwritten by newcommand/newenvironment
WHITELISTED_COMMANDS = [
    "bibliography",
    "newcommand",
    "def",
    "begin",
    "end",
    "section",
    "subsection",
    "subsubsection",
    "paragraph",
    "subparagraph",
    "newline",
    "maketitle",
    "title",
    "author",
    "and",
    "thanks",
    "date",
    "part",
    "chapter",
    "abstract",
    "table",
    "figure",
    "cite",
    "citep",
    "citet",
    "caption",
    "captionof",
    "bibitem",
    "url",
    "ref",
    "appendix",
    "appendices",
    "\\",
    "\\\\",
    # text font
    "textbf",
    "textit",
    "textsl",
    "textsc",
    "textsf",
    "texttt",
    "textrm",
    "textup",
    "emph",
    # text size
    "texttiny",
    "textscriptsize",
    "textfootnotesize",
    "textsmall",
    "textnormal",
    "textlarge",
    "texthuge",
    "text",
    # legacy font
    # Basic text style commands
    "tt",
    "bf",
    "it",
    "sl",
    "sc",
    "sf",
    "rm",
    "em",
    "bold",
    # Font family declarations
    "rmfamily",
    "sffamily",
    "ttfamily",
    # Font shape declarations
    "itshape",
    "scshape",
    "upshape",
    "slshape",
    # Font series declarations
    "bfseries",
    "mdseries",
    # Font combinations and resets
    "normalfont",
    # Additional text mode variants
    "textup",
    "textnormal",
    "textmd",
    # math stuff (often used directly before math mode)
    "unboldmath",
    "boldmath",
    "mathversion",
    # Basic size commands
    "tiny",
    "scriptsize",
    "footnotesize",
    "small",
    "normalsize",
    "large",
    "Large",
    "LARGE",
    "huge",
    "Huge",
    # Additional size declarations
    "smaller",
    "larger",
]


WHITELISTED_ENVIRONMENTS = ["abstract", "table", "figure"]
